# Created 2025-08-21 Thu 21:14
#+title: How to BANISH myself
#+date: [2018-04-18 Wed]
#+author: stardiviner
* WARNING (警告)
:PROPERTIES:
:ID:       4e0a9294-af15-4407-8de3-231f5490c17c
:PUBDATE:  <2019-08-14 Wed 19:46>
:END:

If you feel pain after you saw this. Please be careful!!!
I can't cure your pain inside. Only yourself can figure out a way!!! Just like me now.

如果你看了我的文章后，感到痛苦，那么请小心谨慎。
我无法解除你心中的疑惑和痛苦，只有你自己可以找到出路。就像现在的我一样。
* Set my mind free at first (没有固定的思想规则)
:PROPERTIES:
:ID:       0ef4edc7-1e6e-4318-9f16-3fdfc4ad1406
:PUBDATE:  <2019-08-14 Wed 19:46>
:END:

I first learned that this world has not static rules of though, society trends.
This is the main thing I learned from most of my experience and knowledge. Don't
let specific thing rule my thought. Then I will be able to think free.
Everything is not static anymore. They're changing, dynamiclly changing.

我最开始懂得的是这个世界没有固定的规则。“法无定法”，一切思想和社会规则都不是固
定的。就像时代的改变。不要让一些事物规则限定我自己的思想。那样我就能自由的思考。
万事万物都不再是固定的。它们时刻在动态地发生变化。
* Set my body free then (解除肉身的限制)
:PROPERTIES:
:ID:       521320fe-2999-4592-919c-5f54d202c1bd
:PUBDATE:  <2019-08-14 Wed 19:46>
:END:

Set mind free is hard for most people, they have diffcult to accept new thought,
to enbrace thought freedom. It is not hard for me. The more diffcult step is to
set body free. You will realize that want a free wolking on world in reality
instead of mind world is very hard. You're limited by your nation and area at
first, then you're limited by your environment around things.

让自己的思想自由并非是一件容易的事，人们对于接受新的思想有障碍。我自认为相对于很
多人要容易些。不过更难的是让肉身自由。当你思想自由了之后，你会意识到要想自由行走
在这个世间是一件比解放思想更加困难得多的事情。你一出生就被国家地域附加了身份，然
后你出生后，不断地被周遭的环境附加更多的东西，千丝万缕，红尘万丈。
* I try to be free (我想要自由之身)
:PROPERTIES:
:ID:       08366403-109c-42bb-bcf1-617ffdb88739
:PUBDATE:  <2019-08-14 Wed 19:46>
:END:

Now my free mind is limited by reality. I feel hard, inside. I need to figure
out a way to get out.

现在，虽然思想自由了，但是就像身陷囹圄，无法自由行走。我需要找到一条出路。

I will learn some skills that allow me to live anywhere, no place limitation.
Learn programming and get information and sell based on it. Like this living on
Internet is a good way to be free to go anywhere, touch anything.

我要学习一些能让我在任何地方生存的技能，没有限制。学习编程，在互联网上获取信息，
然后以此发展为生是一个不错的主意。是的，以互联网为生。这样就可以在互联网将变得无
所不在的趋势下找到生存的基础。
* Live on Internet (以互联网为生)
:PROPERTIES:
:ID:       63def87d-a956-4f8f-ab45-cc9d483c5904
:PUBDATE:  <2019-08-14 Wed 19:46>
:END:

Information time, how to make use of this time evolution?

互联网最大的基础就是信息，所谓信息时代嘛。我该如何以此为生？
